athena_password: ENC[AES256_GCM,data:uwIzpPDATXEr8X7lGx5S5k2Bm+QlFnI=,iv:q3jLb9f1yJqn+c5nu5qAA+K1JFNW0PQqPDoeS65f2hc=,tag:zke6/Xo1nVu5tjytfe6cpQ==,type:str]
hermes_password: ENC[AES256_GCM,data:QNKMFBURdHN2LQqtcZv/GtbE,iv:WSx9mkswzuTgaCGgltz+9NL3rOsGyCUuIpVcxKn23G0=,tag:JFokzP2qmCSyTh9vKMFU5Q==,type:str]
sops:
    age:
        - recipient: age1tmfenu0j7epykv2uuu8qugpy3fzpm7zvjgcwgc78z2ddjh74up5qthjwjc
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAxcHFidnQ3QTZjTUo0T1Ft
            amIzR2lMMWdWWkpJV1dZRm9YaXNDVU1aaVhFCk02MVEwZkJod2F0SUNUMi9NMFg5
            NXpBbjNPY2E1bE1FTlF6MVhEaTVUQzAKLS0tIEkwbElUbTAwMDdLVEV1RXJIU2h2
            dnJHeTB6NU9IKzEwdFduM0xPdHNuUmcKY28ajntX/Tzp0hvha174mFsjp4uVtma4
            pXJAGZiKEaltcEntpzeFdVQX4oT3P7+wyB9jO4Pu8pzQcrr+UCpeiw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age18qjctqm7ulf6yqjvrrkmk5j9lf9yw4ljc3zq03429vdlu40wu38s27yhmv
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB0TjZlVFZWM0tDZ1ZtaWpy
            S3FyTnRYWjVaYTltR3hrUmN1WUxycnN1d2s0CkorT2ZPamcxd2o1T1M4SE9HcWQy
            REt2Q2JwN1loTjY5WDN0N095T28wazgKLS0tIFcveVdtZnNONHZwOHRCU2pjcHV1
            MXJsbmhXVlFMeHZWY2RMWWZLdVdlL1UKzFfDhACzDzUYwIOFC0xsOteI6sCB03iQ
            xU5t3Mse3FnJQ4SB5H+aAPCNUG5Uo19YKdf3ly0m3vHgUMkcYQ0sHQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-07-14T08:09:39Z"
    mac: ENC[AES256_GCM,data:/thH8Qmfu9WOpXVW/pZXT2IO+pKOU4MIgMuYTw1z4AFE9MuAyWlLgKhYmcVyPrnzzUlWg7Op8v8I3zgAflyNDyx91pSFATZwUDACVa4mZ4EcaB04k3c0/3Fl7zSVM5jUveqNG5XXEfWE+zvY3x5SmvfsW3c106tVHTHCfAlzyU8=,iv:j0IUgQZM1T2g+olOoUxfc20f2H8eghcU0VW5pmerEgM=,tag:Ntq6JU7ddrin1tQW0Q+k2w==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.10.2
