user_password: ENC[AES256_GCM,data:2YQIMwgsCdzFz3cuFPBGk320ECtsvTdqqm0CAQQLeNwvmENdwxc7bH7px7ySpi1D7D72qtdJdaRvVmyc/maTpi6o1lfbPnJ9ZIROLG3r8I3WiLEOUdK159MdGtzHOYfZtw70NJyd6huzZA==,iv:FuDEBI5Hn6y0l5qAEiNQJ/MTB6qnCYaYcyW7tsoIXdU=,tag:KmmFhYULUl0BpQmKpUUpwQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1tmfenu0j7epykv2uuu8qugpy3fzpm7zvjgcwgc78z2ddjh74up5qthjwjc
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBZODdDUFhrVjRwUTNDZmxN
            dmt3RTg0S1BlTGRxK3hNUEFZMlFsUzY4bHlJCmkzK0FIalN4M29RRzc3S3JET3hM
            alJ6cElRd3haVElUdnBSMjNWWlNSM2MKLS0tIEg0N25kd24rQWN4NUFIT1dYVnN6
            N2VEZjJaOGJrZTBGcCtEUkV1T2NtcTQKuZKw9TLx0qMV7WijWsxXNUPE5NsAWR2I
            XOy0gcz3flGmiEuIbvcZO3n8esjaE6tuMtRjf+bvXFX337GR35GUjQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-06-18T10:47:16Z"
    mac: ENC[AES256_GCM,data:kMA/VPu4v9JCQFlCDjUsKOWy8Bod9slEUZDTb2qEqkDkb0Icm4vhVT88dGqJWGvtEF6im13AFlGg56wGqS6JAZ5jdxXb6nGabRxMchCdAWV+k/2Kg86dfobeNT6FZbyLZso+7qPc4kXlT6iAYTiBnkaGNPVw+gFqTlNlyoyOcpc=,iv:GAekugk7f9c1nESBfMZNgFlaj3+tU5Rw86LXb/S+694=,tag:Nvl5DYNzk/tsskAzjYH8pg==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.9.4
